export default catalog = [
    { cat: 1, 
        artist: 'Mary Lattimore', 
        title: 'Bandage Contacts', 
        path: require(`../assets/mary-lattimore.mp3`), 
        cover: require('../assets/mary-lattimore.gif'), 
        description: 'misty, barely there',  
        color: '#e6e6ff', 
        info: `I wrote this after taking my friend to the hospital in an emergency.\n\nI used copper handbells, Lyon & Healy Style 30 concert grand harp and Moog Mother-32`}, 
    { cat: 2, 
        artist: 'Eluvium', 
        title: 'Dragonfly Lake, North Carolina', 
        path: require(`../assets/xhptest.mp3`), 
        cover: require('../assets/2.gif'), 
        description: 'gentle, pastoral',  
        color: '#80aaed', 
        info: `I was working a lot of late nights in Brooklyn in 2017 during the three week sessions recording the 'Corgi Party' score. We got a substantially cheaper rate using the studio during the off-hours, so sessions would begin around 11pm and go to about 8am. This meant most of my sleeping was done while Brooklyn's various go-getters, creatives and drones were flitting about in their various commutes, lunch breaks, traffic jams, arguments and conversations. Around day 3 I realized I needed something to drown out the cacophony. Before the night's session, I brewed up this track using a MiniMoog Model D for the washes of low end, and a stylophone through a RAT pedal for the high end. It helped me sleep soundly for the next two weeks.`},
    { cat: 3, 
        artist: 'Kelly Moran', 
        title: 'Keybfuzz_009', 
        path: require(`../assets/xlgtest.mp3`), 
        cover: require('../assets/3.gif'), 
        description: 'colorful, lively',  
        color: '#1a1aff', 
        info: `I was working a lot of late nights in Brooklyn in 2017 during the three week sessions recording the 'Corgi Party' score. We got a substantially cheaper rate using the studio during the off-hours, so sessions would begin around 11pm and go to about 8am. This meant most of my sleeping was done while Brooklyn's various go-getters, creatives and drones were flitting about in their various commutes, lunch breaks, traffic jams, arguments and conversations. Around day 3 I realized I needed something to drown out the cacophony. Before the night's session, I brewed up this track using a MiniMoog Model D for the washes of low end, and a stylophone through a RAT pedal for the high end. It helped me sleep soundly for the next two weeks.`}, 
    { cat: 4, 
        artist: 'Owen Pallett', 
        title: 'Noise Organ', 
        path: require(`../assets/owen-pallett.mp3`), 
        cover: require('../assets/1.gif'), 
        description: 'muggy, nocturnal', 
        color: '#000099', 
        info: `I was working a lot of late nights in Brooklyn in 2017 during the three week sessions recording the 'Corgi Party' score. We got a substantially cheaper rate using the studio during the off-hours, so sessions would begin around 11pm and go to about 8am. This meant most of my sleeping was done while Brooklyn's various go-getters, creatives and drones were flitting about in their various commutes, lunch breaks, traffic jams, arguments and conversations. Around day 3 I realized I needed something to drown out the cacophony. Before the night's session, I brewed up this track using a MiniMoog Model D for the washes of low end, and a stylophone through a RAT pedal for the high end. It helped me sleep soundly for the next two weeks.`},

    { cat: 5, 
        artist: 'clipping.', 
        title: 'Space Channel Slaughterhouse', 
        path: require(`../assets/xthtest.mp3`), 
        cover: require('../assets/5.gif'), 
        description: 'harsh, suffocating',  
        color: '#000066', 
        info: `I was working a lot of late nights in Brooklyn in 2017 during the three week sessions recording the 'Corgi Party' score. We got a substantially cheaper rate using the studio during the off-hours, so sessions would begin around 11pm and go to about 8am. This meant most of my sleeping was done while Brooklyn's various go-getters, creatives and drones were flitting about in their various commutes, lunch breaks, traffic jams, arguments and conversations. Around day 3 I realized I needed something to drown out the cacophony. Before the night's session, I brewed up this track using a MiniMoog Model D for the washes of low end, and a stylophone through a RAT pedal for the high end. It helped me sleep soundly for the next two weeks.`},]
